services:
  db:
    container_name: personal_vault
    image: postgres:18-alpine
    restart: unless-stopped
    platform: linux/arm64
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-personal_vault}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: redis
    restart: unless-stopped
    image: redis:8-alpine
    platform: linux/arm64
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    command: redis-server --requirepass ${REDIS_PASSWORD:-redis}

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  default:
    name: personal_vault_network
